### PR TITLE
Add `member_activity_only` configuration option

### LINKED ISSUE #19: repository: make it possible to consider issues/PRs only for known members
https://github.com/con/solidation-con/blob/master/reports/2023-02-20.md#non-con-member-issues-activeopened-in-the-last-7-days shows the tricky use case we have.  I think we should keep monitoring our occasional work within repositories such as `dandi-archive`. But there we are not main maintainers/developers, so 
- we aren't really interested in listing all of the issues filed by main developers as issues from someones who "is not from CON"
- we are interested in all issues/PRs which fall in the other categories and which are owned or assigned to CON members.

I see two possible ways we could "specify" such "special nature" of some repos

- per repo, do similar to #18 - add ability to specify per each repo some attribute like `foreign: True` thus indicating that we are not interested to "own"/attend to all the issues/PRs 
- add higher level `foreign_repositories` listing, so it would make it easy to just list all of those separately.

WDYT @jwodder ?

### PR DESCRIPTION
**Pull request by jwodder**
Closes #19.

### CODE REVIEW

**Comment by yarikoptic** [comment]
<details>
<summary>Testing on this configuration</summary> 

```yaml
project: CON

organizations:
  - name: con
    member_activity_only: false
    fetch_members: true

repositories:
  # might got away since mostly autogenerated but has issues ATM:
  - dandi/dandi-api-webshots-tools
  - dandi/dandi-archive
  - dandi/dandi-cli
  - name: dandi/dandi-hub
    member_activity_only: true
  - dandi/dandi-schema
  - dandi/dandisets
  - dandi/dandisets-healthstatus
  - dandi/example-notebooks
  - dandi/handbook
  - dandi/helpdesk
  - dandi/zarr_checksum
  - name: datalad/datalad
    member_activity_only: true
  - datalad/datalad-container
  - datalad/datalad-crawler
  - datalad/datalad-deprecated
  - name: datalad/datalad-metadata
    member_activity_only: true
  - datalad/datalad-fuse
  - datalad/datalad-installer
  - datalad/datalad-neuroimaging
  - datalad/datalad-registry
  - datalad/datasets.datalad.org
  - datalad/git-annex
  - neurodebian/dockerfiles
  - neurodebian/neurodebian
  - nipy/heudiconv
  - ReproNim/containers
  - ReproNim/reproin
  - ReproNim/reproman
  - ReproNim/reprostim

  # really external but where we are involved/maintainers etc
  - name: DanielDent/git-annex-remote-rclone  # yarikoptic
    member_activity_only: true
  - TheChymera/neuralynx_nwb  # TheChymera, yarikoptic

  # not including those for now but want to list since we need to account for work
  # in them but not really care about any issues
  # Should not participate in "Non-CON member issues active/opened", "Max 10 oldest" etc
  - name: bids-standard/bids-specification  # yarikoptic, TheChymera
    member_activity_only: true
  - name: NeurodataWithoutBorders/matnwb
    member_activity_only: true
  - name: NeurodataWithoutBorders/pynwb
    member_activity_only: true
  - name: hdmf-dev/hdmf
    member_activity_only: true
  - name: fsspec/filesystem_spec
    member_activity_only: true

  # packaging feedstocks -- we need to be alerted and keep them clean etc
  - conda-forge/annexremote-feedstock
  - conda-forge/dandi-feedstock
  - conda-forge/git-annex-feedstock

members:
  # consultants, I will just add them in as well
  - joeyh
  - vmdocua
  # - vsoch? for con/tributors etc?
  # - Vasyl might not be on github, only on Debian gitlab
  # and we are not monitoring there yet  https://salsa.debian.org/basilgello

```
</details>

<details>
<summary>gives me errors</summary> 

```shell
2023-02-24T10:55:00-0500 [INFO    ] solidation: solidation 0.0.0.post17+gff5f9ca
Traceback (most recent call last):
  File "/home/yoh/miniconda-3.10/envs/solidation/bin/solidation", line 8, in <module>
    sys.exit(main())
  File "/home/yoh/miniconda-3.10/envs/solidation/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoh/miniconda-3.10/envs/solidation/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/yoh/miniconda-3.10/envs/solidation/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoh/miniconda-3.10/envs/solidation/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/yoh/miniconda-3.10/envs/solidation/lib/python3.10/site-packages/solidation/__main__.py", line 315, in main
    cfg = Configuration.parse_obj(YAML(typ="safe").load(fp))
  File "pydantic/main.py", line 527, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 9 validation errors for Configuration
repositories -> 3
  str type expected (type=type_error.str)
repositories -> 11
  str type expected (type=type_error.str)
repositories -> 15
  str type expected (type=type_error.str)
repositories -> 29
  str type expected (type=type_error.str)
repositories -> 31
  str type expected (type=type_error.str)
repositories -> 32
  str type expected (type=type_error.str)
repositories -> 33
  str type expected (type=type_error.str)
repositories -> 34
  str type expected (type=type_error.str)
repositories -> 35
  str type expected (type=type_error.str)

```
</details>

what did I do wrong?

**Comment by jwodder** [comment]
@yarikoptic This PR handles the given configuration just fine.  You don't seem to have actually installed this PR branch, based on the logged version number.

**Comment by yarikoptic** [comment]
indeed -- I had `solidation` installed not for development (as I assumed), sorry for the noise on that.

Running 

<details>
<summary>on adjusted config</summary> 

```yaml
project: CON

organizations:
  - name: con
    member_activity_only: false
    # CON has too many overall!  we need to fetch some team(s)
    # fetch_members: true

repositories:
  # might got away since mostly autogenerated but has issues ATM:
  - dandi/dandi-api-webshots-tools
  - dandi/dandi-archive
  - dandi/dandi-cli
  - name: dandi/dandi-hub
    member_activity_only: true
  - dandi/dandi-schema
  - dandi/dandisets
  - dandi/dandisets-healthstatus
  - dandi/example-notebooks
  - dandi/handbook
  - dandi/helpdesk
  - dandi/zarr_checksum
  - name: datalad/datalad
    member_activity_only: true
  - datalad/datalad-container
  - datalad/datalad-crawler
  - datalad/datalad-deprecated
  - name: datalad/datalad-metadata
    member_activity_only: true
  - datalad/datalad-fuse
  - datalad/datalad-installer
  - datalad/datalad-neuroimaging
  - datalad/datalad-registry
  - datalad/datasets.datalad.org
  - datalad/git-annex
  - neurodebian/dockerfiles
  - neurodebian/neurodebian
  - nipy/heudiconv
  - ReproNim/containers
  - ReproNim/reproin
  - ReproNim/reproman
  - ReproNim/reprostim

  # really external but where we are involved/maintainers etc
  - name: DanielDent/git-annex-remote-rclone  # yarikoptic
    member_activity_only: true
  - TheChymera/neuralynx_nwb  # TheChymera, yarikoptic

  # not including those for now but want to list since we need to account for work
  # in them but not really care about any issues
  # Should not participate in "Non-CON member issues active/opened", "Max 10 oldest" etc
  - name: bids-standard/bids-specification  # yarikoptic, TheChymera
    member_activity_only: true
  - name: NeurodataWithoutBorders/matnwb
    member_activity_only: true
  - name: NeurodataWithoutBorders/pynwb
    member_activity_only: true
  - name: hdmf-dev/hdmf
    member_activity_only: true
  - name: fsspec/filesystem_spec
    member_activity_only: true

  # packaging feedstocks -- we need to be alerted and keep them clean etc
  - conda-forge/annexremote-feedstock
  - conda-forge/dandi-feedstock
  - conda-forge/git-annex-feedstock

members:
  - yarikoptic
  - andycon
  - jwodder
  - TheChymera
  - asmacdo
  - candleindark
  # consultants, I will just add them in as well
  - joeyh
  - vmdocua
  # - vsoch? for con/tributors etc?
  # - Vasyl might not be on github, only on Debian gitlab
  # and we are not monitoring there yet  https://salsa.debian.org/basilgello

```
</details>

<details>
<summary>results in 404</summary> 

```shell
2023-02-24T11:49:12-0500 [INFO    ] solidation: Processing repo datalad/datalad-deprecated
Traceback (most recent call last):
  File "/home/yoh/miniconda-3.10/envs/solidation/bin/solidation", line 8, in <module>
    sys.exit(main())
  File "/home/yoh/miniconda-3.10/envs/solidation/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoh/miniconda-3.10/envs/solidation/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/yoh/miniconda-3.10/envs/solidation/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoh/miniconda-3.10/envs/solidation/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/datasets/con/solidation-con/code/src/solidation/__main__.py", line 395, in main
    report = cs.run()
  File "/mnt/datasets/con/solidation-con/code/src/solidation/__main__.py", line 117, in run
    repo = self.gh.get_repo(repospec.name)
  File "/home/yoh/miniconda-3.10/envs/solidation/lib/python3.10/site-packages/github/MainClass.py", line 330, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
  File "/home/yoh/miniconda-3.10/envs/solidation/lib/python3.10/site-packages/github/Requester.py", line 353, in requestJsonAndCheck 
    return self.__check(
  File "/home/yoh/miniconda-3.10/envs/solidation/lib/python3.10/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest/reference/repos#get-a-repository"}

```
</details>

 -- but repo is there (if it is about `datalad/datalad-deprecated`) . any clues what it is complaining about?

**Comment by jwodder** [comment]
@yarikoptic The error actually occurred for `datalad/datalad-metadata`, which does not exist (or at least I can't access it either).  The "Processing repo" message is emitted *after* the repo is fetched; there's a "Fetching repo" message emitted before fetching, but that's at DEBUG level.

**Comment by yarikoptic** [comment]
d'oh, thanks!  we should fix confusing messaging -- I assume `'ing` to be smth about to be done now not done already

**Comment by jwodder** [comment]
@yarikoptic I've increased the log level of the "Fetching repo" message to INFO.

**Comment by yarikoptic** [comment]
Looking at https://github.com/con/solidation-con/blob/9bd468a3aabb85b51f2542007a2600299887a482/reports/2023-02-24-foreign.md  I think it does the right thing!  Thank you @jwodder !

**Pull request merged**
