### PR TITLE
Increase minimum Python version to 3.10

### PR DESCRIPTION
**Pull request by jwodder**

### CODE REVIEW

**Comment by yarikoptic** [comment]
Could we shelve this for now per https://github.com/con/solidation/pull/36#discussion_r1388303507 ?

**Comment by jwodder** [comment]
@yarikoptic Why?  Couldn't you just run solidation inside a Python 3.10 environment procured with Conda?

**Comment by yarikoptic** [comment]
ok.
- added your @jwodder ssh key to con account on smaug in case of future need for troubleshooting fixing under it
- produced new miniconda installation with an env using 1 command: `datalad-installer -E ~/miniconda3.sh miniconda --batch -c conda-fore --path ~/miniconda3 conda-env --name versations --spec python==3.10` and then just commended out that `conda activate versations` within `~/miniconda3.sh` so we could reuse it for other ones too (attn @asmacdo -- this is an invocation I told you about in the car). I called it `versations`, not `solidation` env just reflecting current name within `/mnt/datasets/con/matrix-archive/tools/.venvs/versations/bin/activate`
- did `/mnt/datasets/con/matrix-archive/tools/solidation$ pip install -e .`
- did `/mnt/datasets/con/matrix-archive/tools/versations$ pip install -e .`

@asmacdo - do you remember if we need anything else to be done for `versations` for cron job to operate properly? if we are to do the switch we would need to modify those "cron" scripts we have and should be ready to accept this PR and update the state of `solidation` submodule there.

**Comment by asmacdo** [comment]
It could cause trouble if `versations` doesn't work > 3.9.  I think we'll be ok, but I say lets just merge it and I'll fix versations if it doesnt work :)

**Comment by jwodder** [comment]
@yarikoptic So is this mergeable now?

**Pull request merged**
